// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type ActiveSession struct {
	ID          int64
	ProgramName string
	StartTime   time.Time
}

type SessionHistory struct {
	ID              int64
	ProgramName     string
	StartTime       time.Time
	EndTime         time.Time
	DurationSeconds int64
}

type TrackedProgram struct {
	ID              int64
	Name            string
	LifetimeSeconds int64
}
