// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: session_history.sql

package database

import (
	"context"
	"time"
)

const addToSessionHistory = `-- name: AddToSessionHistory :exec
INSERT INTO session_history (program_name, start_time, end_time, duration_seconds)
VALUES (?, ?, ?, ?)
`

type AddToSessionHistoryParams struct {
	ProgramName     string
	StartTime       time.Time
	EndTime         time.Time
	DurationSeconds int64
}

func (q *Queries) AddToSessionHistory(ctx context.Context, arg AddToSessionHistoryParams) error {
	_, err := q.db.ExecContext(ctx, addToSessionHistory,
		arg.ProgramName,
		arg.StartTime,
		arg.EndTime,
		arg.DurationSeconds,
	)
	return err
}
