// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: session_history.sql

package database

import (
	"context"
	"time"
)

const addToSessionHistory = `-- name: AddToSessionHistory :exec
INSERT INTO session_history (program_name, start_time, end_time, duration_seconds)
VALUES (?, ?, ?, ?)
`

type AddToSessionHistoryParams struct {
	ProgramName     string
	StartTime       time.Time
	EndTime         time.Time
	DurationSeconds int64
}

func (q *Queries) AddToSessionHistory(ctx context.Context, arg AddToSessionHistoryParams) error {
	_, err := q.db.ExecContext(ctx, addToSessionHistory,
		arg.ProgramName,
		arg.StartTime,
		arg.EndTime,
		arg.DurationSeconds,
	)
	return err
}

const getAllSessionsForProgram = `-- name: GetAllSessionsForProgram :many
SELECT id, program_name, start_time, end_time, duration_seconds FROM session_history
WHERE session_history.program_name = ?
ORDER BY start_time DESC
`

func (q *Queries) GetAllSessionsForProgram(ctx context.Context, programName string) ([]SessionHistory, error) {
	rows, err := q.db.QueryContext(ctx, getAllSessionsForProgram, programName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionHistory
	for rows.Next() {
		var i SessionHistory
		if err := rows.Scan(
			&i.ID,
			&i.ProgramName,
			&i.StartTime,
			&i.EndTime,
			&i.DurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountOfSessionsForProgram = `-- name: GetCountOfSessionsForProgram :one
SELECT COUNT(*) FROM session_history
WHERE session_history.program_name = ?
`

func (q *Queries) GetCountOfSessionsForProgram(ctx context.Context, programName string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCountOfSessionsForProgram, programName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLastSessionForProgram = `-- name: GetLastSessionForProgram :one
SELECT id, program_name, start_time, end_time, duration_seconds FROM session_history
WHERE session_history.program_name = ?
ORDER BY end_time DESC
LIMIT 1
`

func (q *Queries) GetLastSessionForProgram(ctx context.Context, programName string) (SessionHistory, error) {
	row := q.db.QueryRowContext(ctx, getLastSessionForProgram, programName)
	var i SessionHistory
	err := row.Scan(
		&i.ID,
		&i.ProgramName,
		&i.StartTime,
		&i.EndTime,
		&i.DurationSeconds,
	)
	return i, err
}

const removeAllRecords = `-- name: RemoveAllRecords :exec
DELETE FROM session_history
`

func (q *Queries) RemoveAllRecords(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, removeAllRecords)
	return err
}

const removeRecordsForProgram = `-- name: RemoveRecordsForProgram :exec
DELETE FROM session_history
WHERE session_history.program_name = ?
`

func (q *Queries) RemoveRecordsForProgram(ctx context.Context, programName string) error {
	_, err := q.db.ExecContext(ctx, removeRecordsForProgram, programName)
	return err
}
