// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tracked_programs.sql

package database

import (
	"context"
)

const addProgram = `-- name: AddProgram :exec
INSERT INTO tracked_programs (name)
VALUES (?)
`

func (q *Queries) AddProgram(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, addProgram, name)
	return err
}

const getAllProgramNames = `-- name: GetAllProgramNames :many
SELECT name FROM tracked_programs
`

func (q *Queries) GetAllProgramNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllProgramNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProgramByName = `-- name: GetProgramByName :one
SELECT id, name, lifetime_seconds FROM tracked_programs
WHERE name = ?
`

func (q *Queries) GetProgramByName(ctx context.Context, name string) (TrackedProgram, error) {
	row := q.db.QueryRowContext(ctx, getProgramByName, name)
	var i TrackedProgram
	err := row.Scan(&i.ID, &i.Name, &i.LifetimeSeconds)
	return i, err
}

const removeAllPrograms = `-- name: RemoveAllPrograms :exec
DELETE FROM tracked_programs
`

func (q *Queries) RemoveAllPrograms(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, removeAllPrograms)
	return err
}

const removeProgram = `-- name: RemoveProgram :exec
DELETE FROM tracked_programs
WHERE name = ?
`

func (q *Queries) RemoveProgram(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, removeProgram, name)
	return err
}

const updateLifetime = `-- name: UpdateLifetime :exec
UPDATE tracked_programs
SET lifetime_seconds = lifetime_seconds + ?
WHERE name = ?
`

type UpdateLifetimeParams struct {
	LifetimeSeconds int64
	Name            string
}

func (q *Queries) UpdateLifetime(ctx context.Context, arg UpdateLifetimeParams) error {
	_, err := q.db.ExecContext(ctx, updateLifetime, arg.LifetimeSeconds, arg.Name)
	return err
}
